// Code generated by Axiom CLI; DO NOT EDIT.

// Package axiom provides the Context interface and all platform capabilities
// injected into every node function.
//
// All capabilities are accessed through the single ax parameter:
//
//	ax.Log().Info("order processed", "order_id", "abc123", "total", 99.99)
//	apiKey, ok := ax.Secrets().Get("ANTHROPIC_API_KEY")
//
// Adding new platform capabilities requires no change to node function
// signatures — they are accessed via the Context interface.
package axiom

// Logger is a structured logger pre-configured for a single node invocation.
// Concurrent invocations each receive their own Logger instance — never share
// a Logger across calls. The platform injects it via Context; node authors
// never construct one directly.
type Logger interface {
	Debug(msg string, args ...any)
	Info(msg string, args ...any)
	Warn(msg string, args ...any)
	Error(msg string, args ...any)
}

// SecretStatus is the typed result of Secrets.Status(name) — ADR-156.
//
// Get(name) alone returns ("", false) both when a secret was revoked after
// execution start and when it was never configured at all — a node cannot
// tell "re-authorize this credential" from "check axiom.yaml" from that
// result alone. Use Status when the distinction matters.
type SecretStatus int

const (
	// SecretStatusAvailable means the secret currently resolves to a value;
	// Get(name) returns it.
	SecretStatusAvailable SecretStatus = iota
	// SecretStatusRevoked means the secret existed in this execution's
	// initial snapshot but no longer resolves against the live vault — it
	// was deleted or revoked after the execution started. Get(name) returns
	// ("", false).
	SecretStatusRevoked
	// SecretStatusUnset means the secret was never present for this node —
	// never configured by the tenant, or (for a non-owned node) not
	// authorized. Get(name) returns ("", false), identically to
	// SecretStatusRevoked.
	SecretStatusUnset
)

// Secrets provides read-only access to the tenant secrets resolved by the
// platform at invocation time. Values are plaintext strings; the platform
// handles encryption and decryption. Node authors never construct a Secrets
// instance directly — the platform injects it via Context on every invocation.
type Secrets interface {
	// Get returns the value for the named secret and true when present.
	// Returns ("", false) when the secret was not resolved for this invocation.
	Get(name string) (string, bool)
}

// SecretStatusOf reports the typed status of a declared secret — ADR-156.
//
// Get(name) alone returns ("", false) both when a secret was revoked after
// execution start and when it was never configured — this helper tells them
// apart. Call it as axiom.SecretStatusOf(ax.Secrets(), "NAME").
//
// ADR-156 (2026-07-20): status is a FREE HELPER, not a method on the Secrets
// interface, precisely so the accessor is BACKWARD-COMPATIBLE: adding a method
// to Secrets would break every existing node's hand-written test double (and
// any other implementer) at recompile time. When the Secrets implementation is
// the platform's, this reports the real Available/Revoked/Unset distinction; a
// double that only implements Get degrades to Available (present) or Unset
// (absent) — never a false Revoked.
func SecretStatusOf(s Secrets, name string) SecretStatus {
	if sr, ok := s.(interface {
		Status(string) SecretStatus
	}); ok {
		return sr.Status(name)
	}
	if _, ok := s.Get(name); ok {
		return SecretStatusAvailable
	}
	return SecretStatusUnset
}

// ADR-129 (2026-07-11): agentic memory (ax.Agent().Memory()) is out of scope
// for beta and has been removed from the node SDK entirely — a shared
// marketplace node's memory proxy stamped the deploy-time publisher tenant,
// letting unrelated tenants composing the same node read each other's memory
// (see the ADR for the full trust-boundary analysis). Removing the client
// surface here closes the reachable path at compile time. The backend
// (internal/memory, proto/memory, MemoryService) is retained for post-beta.

// ADR-050 (2026-05-26): ax.Reflection().Flow() — read-only view of the
// running flow graph + current execution position. Surfaced as
// ax.reflection.flow.* in the Python SDK; the Go interface namespaces it
// under Reflection() so future per-domain reflection surfaces (Execution,
// Tenant) can land without breaking signatures.

// ReflectionNode is one node placement in the running flow. The InputMessageName
// and OutputMessageName are fully-qualified proto names; field-level
// introspection is not yet exposed.
type ReflectionNode struct {
	InstanceID        uint32
	NodeULID          string
	Name              string
	PackageName       string
	PackageVersion    string
	NodeType          string // "node" | "subflow" | "pipeline"
	InputMessageName  string
	OutputMessageName string
	CanvasNodeID      string
	GridCol           int32 // ADR-086: coarse-grid column (flow depth, left->right)
	GridRow           int32 // ADR-086: coarse-grid row (parallel lane, top->down)
}

// ConditionSummary is the agent-readable digest of an edge's dispatch
// condition (ADR-055 / GAP-4 (2026-05-29)). It lets a node see WHAT an edge
// dispatches on — e.g. Field="tools", Op="EQ", Operands=["ToolX"] means
// "ToolX" ∈ tools — so it can make idempotent decisions (skip re-adding an
// already-wired tool) without the compiled CEL.
type ConditionSummary struct {
	Field    string   // dotted field path, e.g. "tools"
	Op       string   // short op name (EQ | NEQ | CONTAINS | ...)
	Operands []string // comparison operand(s)
}

// ReflectionEdge is one edge (forward or loop) in the running flow.
// HasCondition / HasAdapter are structural flags only — the compiled
// CEL/adapter recipe itself is not exposed by design. MaxIterations is
// meaningful only for entries returned by FlowReflection.LoopEdges().
// ADR-055 (2026-05-29): ConditionSummary exposes the leaf predicate
// (field/op/operands) when the edge is conditional, else nil.
type ReflectionEdge struct {
	SrcInstance      uint32
	DstInstance      uint32
	CanvasEdgeID     string
	HasCondition     bool
	HasAdapter       bool
	MaxIterations    uint32
	ConditionSummary *ConditionSummary
}

// FlowPosition describes where the current invocation sits in the running flow.
type FlowPosition struct {
	CurrentInstance      uint32
	Depth                uint32            // 0 at the root flow
	LoopIterations       map[uint32]uint32 // keyed by loop-head dst_instance
	SubflowStackGraphIDs []string          // root → immediate parent
}

// FlowReflection is the read-only view of the running flow graph + position.
// Obtain via ax.Reflection().Flow().
type FlowReflection interface {
	Nodes() []ReflectionNode
	Edges() []ReflectionEdge
	LoopEdges() []ReflectionEdge
	Position() FlowPosition
	GraphID() string
}

// Reflection is the reflection capability bundle. Today exposes only Flow();
// future surfaces (Execution, Tenant) land here without changing node
// function signatures.
type Reflection interface {
	Flow() FlowReflection
}

// Context is the single platform capability injection point for every node
// handler function. It is passed as the second parameter (ax) to every handler:
//
//	func MyNode(ctx context.Context, ax axiom.Context, input *gen.MyRequest) (*gen.MyResponse, error) {
//	    ax.Log().Info("handling", "id", input.GetId())
//	    key, ok := ax.Secrets().Get("MY_SECRET")
//	    ...
//	}
//
// Adding new platform capabilities requires no change to existing node
// function signatures — all capabilities are accessed via methods on Context.
type Context interface {
	// Log returns the structured logger for this invocation. Use instead of fmt.Println.
	Log() Logger

	// Secrets returns the tenant secrets resolver for this invocation.
	// Use for API keys and connection strings.
	Secrets() Secrets

	// ExecutionID returns the ID of the current execution.
	ExecutionID() string

	// FlowID returns the stable ID of the graph artifact (constant across executions).
	FlowID() string

	// TenantID returns the ID of the tenant that owns this invocation.
	TenantID() string

	// Reflection returns the read-only view of the running flow.
	// Today: ax.Reflection().Flow(). Future: Execution(), Tenant().
	// See ADR-050 (2026-05-26).
	Reflection() Reflection

	// Mutation returns the mid-execution flow-mutation surface.
	// Today: ax.Mutation().Flow().AddNode / AddEdge. See ADR-051.
	Mutation() Mutation
}

// TelemetryOf returns the tenant-safe telemetry surface for this invocation
// (ADR-073). It is a package-level accessor rather than a Context method on
// purpose: adding a method to the Context interface would break every existing
// package's committed test double. In production it buffers to the sidecar (the
// sole collector egress); under `axiom dev` / unit tests it is a no-op.
//
//	axiom.TelemetryOf(ax).AddEvent("cache_hit", axiom.Int("size", 42))
func TelemetryOf(ax Context) Telemetry {
	if c, ok := ax.(telemetryCarrier); ok {
		return c.AxiomTelemetry()
	}
	return noopTelemetry{}
}

// telemetryCarrier is implemented by the production AxiomContext so TelemetryOf
// can reach the per-invocation buffer without touching the Context interface.
type telemetryCarrier interface{ AxiomTelemetry() Telemetry }

type noopTelemetry struct{}

func (noopTelemetry) AddEvent(string, ...Attr)          {}
func (noopTelemetry) Counter(string, float64, ...Attr)  {}
func (noopTelemetry) Histogram(string, float64, ...Attr) {}

// Telemetry is the tenant-safe node telemetry surface (ADR-073). All calls buffer
// in-process and are flushed to the sidecar on handler return; the sidecar is the
// sole collector egress. Secret-keyed attributes are dropped at the sidecar.
type Telemetry interface {
	// AddEvent records a named event (with optional attributes) on the node's
	// invocation span.
	AddEvent(name string, attrs ...Attr)
	// Counter adds value to a named custom counter (metric axiom_node_<name>).
	Counter(name string, value float64, attrs ...Attr)
	// Histogram records value into a named custom histogram.
	Histogram(name string, value float64, attrs ...Attr)
}

// Attr is a typed telemetry attribute. Build one with String/Int/Float/Bool.
// Value holds string | int64 | float64 | bool.
type Attr struct {
	Key   string
	Value any
}

// String/Int/Float/Bool construct a typed telemetry Attr.
func String(key, value string) Attr { return Attr{Key: key, Value: value} }
func Int(key string, value int64) Attr { return Attr{Key: key, Value: value} }
func Float(key string, value float64) Attr { return Attr{Key: key, Value: value} }
func Bool(key string, value bool) Attr { return Attr{Key: key, Value: value} }

// ADR-051 (2026-05-26): ax.Mutation().Flow().* — append-only mutation
// of the running flow. Nodes declared with mutation_capable: true in
// axiom.yaml may call AddNode / AddEdge during their handler; calls
// buffer locally and are flushed to NodeResponse.MutationBatch on
// return. Rejections surface as MutationError when the next handler
// invocation's request carries a deterministic
// "axiom: mutation rejected: ..." error_message prefix.

// CanvasPosition is an optional layout hint for an added node.
type CanvasPosition struct {
	X float64
	Y float64
	// ADR-086: coarse-grid cell. When set (non-zero), the worker places the
	// node at this cell and derives the pixel position; the canvas snaps to the
	// same grid. GridCol/GridRow take precedence over X/Y.
	GridCol int32
	GridRow int32
}

// EdgeCondition is an optional structural predicate gating a mutation-added
// edge (ADR-054 / GAP-1 (2026-05-29)). A leaf on a repeated field has ANY
// semantics, so {Op:"EQ", Field:"tools", Value:"ToolX"} expresses "ToolX" in
// tools — letting AddTool wire a conditional dispatch edge that fires only on
// turns the reasoner selects it. Structural only — no CEL, no adapter.
type EdgeCondition struct {
	Op    string // EQ | NEQ | LT | LTE | GT | GTE | CONTAINS | ... Empty -> EQ.
	Field string // dotted field path on the source node's output message
	Value string // comparison operand (string form)
}

// FlowMutation is the mutation surface for the running flow.
// AddNode returns the batch-local instance id the SDK has assigned;
// use it on subsequent AddEdge calls within the same handler.
type FlowMutation interface {
	AddNode(packageName, packageVersion string, canvasPosition *CanvasPosition) uint32
	// AddEdge wires an edge from src to dst. Pass a non-nil condition
	// (ADR-054) for a conditional dispatch edge; pass nil for an
	// unconditional edge (v1 behaviour).
	AddEdge(srcInstance, dstInstance uint32, condition *EdgeCondition)
}

// Mutation is the mutation capability bundle. Today exposes only Flow();
// future surfaces (Config) land here.
type Mutation interface {
	Flow() FlowMutation
}

// MutationError is raised when the platform rejects a buffered mutation.
// Message is the human-readable reason (everything after the
// "axiom: mutation rejected: " prefix). The structured engine code is
// not exposed (ADR-051 trust boundary).
type MutationError struct{ Message string }

func (e *MutationError) Error() string { return e.Message }
